In [1]:
import hickle as hkl
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [2]:
emerging_arrays = hkl.load("/Users/jonruiz/Capstone/emerging_arrays.hkl")

In [3]:
established_arrays = hkl.load("/Users/jonruiz/Capstone/established_arrays.hkl") 

In [4]:
type(emerging_arrays)

dict

In [5]:
d = established_arrays["00B7TZ0Xawar6NZ00JFomN"].reshape(1,-1)

In [6]:
f = emerging_arrays["000xYdQfIZ4pDmBGzQalKU"].reshape(1,-1)

In [7]:
cosine_similarity(d, f)

array([[0.95215475]])

In [13]:
cosine_similarity(d, f)[0][0]

0.9521547500566696

In [14]:
recommender = pd.DataFrame(index = emerging_arrays.keys(), columns=established_arrays.keys())

In [10]:
recommender.head()

00B7TZ0Xawar6NZ00JFomN 00EXQo4oF8LyQMa8byKvGM  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN   

                       00FuOCmghgctxEsVVMGKDk 00GOPLxW4PGQuUYdPJh8K1  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN   

                       00Mb3DuaIH1kjrwOku9CGU 00WvmRXTkPBZNhhRK3xfdy  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN   

                       00wyFkzeyMt0qsiQvs9aUE 0A31i51V3omHTJMDCJxDfh  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN   

                       0AHHDAHFRaT82UVw5fMr1R 0AKAxdNkwq9ZxRdW1DN9zW  ...  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN  ...   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN  ...   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN  ...   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN  ...   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN  ...   

                       3803fF96TYnzkSMA0M0L5H 4940HtUKC4VDtiC5s4t4MT  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN   

                       5274I4mUMnYczyeXkGDWZN 5600nq7TiBraBX2jobyJ3l  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN   

                       6156ZPGcezId0Bmw7x7c7K 6908BaPYEQTc9KMAQACod6  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN   

                       7257drAN3eTtaaUUPw95B3 20117nklRrpujknMRpueYQ  \
000xYdQfIZ4pDmBGzQalKU                    NaN                    NaN   
00ANezjn7uJm2J5VWMYcwS                    NaN                    NaN   
00PdQU6lMvLSqa2IyK2U5P                    NaN                    NaN   
00PtvMHnJDylnYKHrs8Z1V                    NaN                    NaN   
00WBIDfWhOh5tlPNehdTuD                    NaN                    NaN   

                       27876bQcDNkZhWqvF0zfFN 33471tzU1VghDg9zNgGRpz  
000xYdQfIZ4pDmBGzQalKU   

In [12]:
[v for k, v in established_arrays.items()]

[array([-35.000822  , -33.1337748 , -31.94509713, ..., -80.        ,
        -80.        , -80.        ]),
 array([-23.07781995, -26.16224623, -28.35463535, ..., -80.        ,
        -80.        , -80.        ]),
 array([ -5.05420985,  -5.37463659,  -8.94179477, ..., -80.        ,
        -80.        , -80.        ]),
 array([-33.64797111, -38.92956083, -41.24379747, ..., -80.        ,
        -80.        , -80.        ]),
 array([-16.41599547, -21.55985427, -28.46106164, ..., -64.07698399,
        -63.69403298, -71.78322028]),
 array([-19.0107763 , -20.94532609, -22.35079457, ..., -63.30272768,
        -68.34459469, -78.9226666 ]),
 array([-22.16376864, -21.51873177, -21.75414391, ..., -80.        ,
        -80.        , -80.        ]),
 array([-28.24291454, -29.06588367, -29.88056453, ..., -52.83893501,
        -57.06617999, -69.07946216]),
 array([-16.73353984, -22.12583708, -37.50903932, ..., -64.58913383,
        -63.63071024, -73.01411766]),
 array([-16.69444359, -13.79336952, -

In [13]:
len(established_arrays.items())

4098

In [15]:
from tqdm import tqdm 
for k, v in established_arrays.items():
    for i, j in tqdm(emerging_arrays.items()):
        try:
            var1 = v.reshape(1, -1)
            var2 = j.reshape(1, -1)
            similarity = cosine_similarity(var1, var2)
            recommender.loc[i,k] = similarity[0][0]
        except:
            recommender.loc[i,k] = 0

  1%|▏         | 62/4407 [21:58<2:14:53,  1.86s/it]   
KeyboardInterrupt



In [17]:
recommender.shape

(4407, 4098)

In [30]:
import random
selection = random.sample(set(recommender.index), 1000)

In [31]:
recommender_model = pd.DataFrame(index = selection, columns=["6mFkJmJqdDVQ1REhVfGgd1","1595LW73XBxkRk2ciQOHfr","04ZTP5KsCypmtCmQg5tH9R","37f4ITSlgPX81ad2EvmVQr", "6uAm7pG66O1XesXS9bpHSF","4PpuH4mxL0rD35mOWaLoKS"])

In [32]:
recommender_model.columns

Index(['6mFkJmJqdDVQ1REhVfGgd1', '1595LW73XBxkRk2ciQOHfr',
       '04ZTP5KsCypmtCmQg5tH9R', '37f4ITSlgPX81ad2EvmVQr',
       '6uAm7pG66O1XesXS9bpHSF', '4PpuH4mxL0rD35mOWaLoKS'],
      dtype='object')

In [33]:
for i in recommender_model.index:
    array1 = emerging_arrays[i]
    var1 = array1.reshape(1,-1)
    for k in tqdm(recommender_model.columns):
        try:
            array2 = established_arrays[k]
            var2= array2.reshape(1,-1)
            similarity = cosine_similarity(var1, var2)
            recommender_model.loc[i,k] = similarity[0][0]
        except:
            recommender_model.loc[i,k] = 0


100%|██████████| 6/6 [00:00<00:00, 177.42it/s]


100%|██████████| 6/6 [00:00<00:00, 200.44it/s]


100%|██████████| 6/6 [00:00<00:00, 109.04it/s]


100%|██████████| 6/6 [00:00<00:00, 171.51it/s]


  0%|          | 0/6 [00:00<?, ?it/s]


100%|██████████| 6/6 [00:00<00:00, 146.56it/s]

In [35]:
established = pd.read_csv("/Users/jonruiz/Capstone/Datasets/established_artists_songs.csv")
emerging = pd.read_csv("/Users/jonruiz/Capstone/Datasets/emerging_artists_songs.csv")

In [39]:
established.head()

Unnamed: 0         track_name           artist  duration  popularity  \
0           0           Bad Liar  Imagine Dragons    260773          88   
1           1           Believer  Imagine Dragons    204346          87   
2           2            Thunder  Imagine Dragons    187146          86   
3           3            Natural  Imagine Dragons    189466          85   
4           4  Whatever It Takes  Imagine Dragons    201240          82   

  release_date  mp3                track_id               artist_id  
0   2018-11-09  NaN  2RSHsoi04658QL5xgQVov3  53XhwfbYqKCa1cC15pYq2q  
1   2017-06-23  NaN  0pqnGHJpmpxLKifKRmU6WP  53XhwfbYqKCa1cC15pYq2q  
2   2017-06-23  NaN  1zB4vmk8tFRmM9UULNzbLB  53XhwfbYqKCa1cC15pYq2q  
3   2018-11-09  NaN  2FY7b99s15jUprqC0M5NCT  53XhwfbYqKCa1cC15pYq2q  
4   2017-06-23  NaN  6Qn5zhYkTa37e91HC1D7lb  53XhwfbYqKCa1cC15pYq2q

In [52]:
established_dict = {}
for i in range(len(established)):
    value = established.track_name[i] + " by " + established.artist[i]
    key = established.track_id[i]
    established_dict[key] = value

In [54]:
emerging_dict = {}
for i in range(len(emerging)):
    value = emerging.track_name[i] + " by " + emerging.artist[i]
    key = emerging.track_id[i]
    emerging_dict[key] = value

In [56]:
recommender_model.rename(index = emerging_dict, columns= established_dict, inplace= True)

In [58]:
recommender_model.head()

Wish You Were Here by Pink Floyd  \
Can You Hear Him by Kamasi Washington                                  0.970757   
Hurts Like Hell (feat. Offset) by Madison Beer                         0.953282   
Dark All Day by Gunship                                                0.961811   
Warrior by Reagan Strange                                              0.961832   
Soltero by Jon Z                                                       0.958239   

                                               A-Punk by Vampire Weekend  \
Can You Hear Him by Kamasi Washington                           0.962985   
Hurts Like Hell (feat. Offset) by Madison Beer                  0.943199   
Dark All Day by Gunship                                         0.952889   
Warrior by Reagan Strange                                       0.951839   
Soltero by Jon Z                                                0.949462   

                                               I'm a Mess by Bebe Rexha  \
Can You Hear Him by Kamasi Washington                          0.965999   
Hurts Like Hell (feat. Offset) by Madison Beer                 0.962027   
Dark All Day by Gunship                                        0.970762   
Warrior by Reagan Strange                                      0.960194   
Soltero by Jon Z                                               0.964352   

                                               Fight Song by Rachel Platten  \
Can You Hear Him by Kamasi Washington                              0.951995   
Hurts Like Hell (feat. Offset) by Madison Beer                     0.930705   
Dark All Day by Gunship                                            0.945081   
Warrior by Reagan Strange                                          0.937777   
Soltero by Jon Z                                                    0.94124   

                                               Good as Hell by Lizzo  \
Can You Hear Him by Kamasi Washington                       0.954662   
Hurts Like Hell (feat. Offset) by Madison Beer              0.954717   
Dark All Day by Gunship                                     0.956675   
Warrior by Reagan Strange                                   0.947462   
Soltero by Jon Z                                            0.950643   

                                               Lemon by N.E.R.D  
Can You Hear Him by Kamasi Washington                  0.946376  
Hurts Like Hell (feat. Offset) by Madison Beer         0.947976  
Dark All Day by Gunship                                0.958556  
Warrior by Reagan Strange                              0.939713  
Soltero by Jon Z                                       0.948386

In [57]:
recommender_model.to_csv("recommender_for_presentation.csv")

In [122]:
search = 'Rachel'

for title in recommender_model.loc[:, recommender_model.columns.str.contains(search)]:
    print(title)
    print('')
    print('10 closest songs')
    print('')
    print(recommender_model.loc[:, title].sort_values(ascending=False)[1:11])
    print('')
    print('*******************************************************************************************')
    print('')

Fight Song by Rachel Platten

10 closest songs

Needing You Now by Meredith Andrews        0.968989
Wolf Totem by The HU                       0.968843
Bittern Wake up Call by Cosmo Sheldrake    0.966343
Alcohol by Gogol Bordello                  0.966059
Not Dead Yet - Rock Mix by LEDGER          0.964567
Red Light by SAFE                          0.964266
Giving Back the Pain by Afterlife          0.964236
Spring Breeze by Wanna One                 0.963997
Woken Furies by Gunship                    0.963686
Never Going Back by Hot Water Music        0.963367
Name: Fight Song by Rachel Platten, dtype: object

*******************************************************************************************



In [124]:
q = input('Enter Song Here')
for title in recommender_model.loc[:, recommender_model.columns.str.contains(search)]:
    inp = recommender_model.loc[:, recommender_model.columns.str.contains(q)]
    print(recommender_model.loc[:, title].sort_values(ascending=False)[1:11])

Enter Song Herelemon
Needing You Now by Meredith Andrews        0.968989
Wolf Totem by The HU                       0.968843
Bittern Wake up Call by Cosmo Sheldrake    0.966343
Alcohol by Gogol Bordello                  0.966059
Not Dead Yet - Rock Mix by LEDGER          0.964567
Red Light by SAFE                          0.964266
Giving Back the Pain by Afterlife          0.964236
Spring Breeze by Wanna One                 0.963997
Woken Furies by Gunship                    0.963686
Never Going Back by Hot Water Music        0.963367
Name: Fight Song by Rachel Platten, dtype: object
